# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from reminiscence.api import reminiscence_pb2 as reminiscence_dot_api_dot_reminiscence__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reminiscence/api/reminiscence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReminiscenceServiceStub(object):
    """Reminiscence gRPC Service - Control Plane API (v0.6.0)

    This service provides remote access to semantic cache operations.
    Designed as the foundation for the dual-plane architecture in v1.0.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/Lookup',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.LookupBatch = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/LookupBatch',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchResponse.FromString,
                _registered_method=True)
        self.Store = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/Store',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.StoreBatch = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/StoreBatch',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/CheckAvailability',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.Invalidate = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/Invalidate',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.InvalidateRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.InvalidateResponse.FromString,
                _registered_method=True)
        self.CleanupExpired = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/CleanupExpired',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredResponse.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/Clear',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.ClearRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.ClearResponse.FromString,
                _registered_method=True)
        self.CreateIndex = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/CreateIndex',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/GetStats',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/GetIndexStats',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsResponse.FromString,
                _registered_method=True)
        self.ListEntries = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/ListEntries',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.GetFlightTicket = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/GetFlightTicket',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/HealthCheck',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/reminiscence.v1.ReminiscenceService/GetCapabilities',
                request_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)


class ReminiscenceServiceServicer(object):
    """Reminiscence gRPC Service - Control Plane API (v0.6.0)

    This service provides remote access to semantic cache operations.
    Designed as the foundation for the dual-plane architecture in v1.0.
    """

    def Lookup(self, request, context):
        """Core Cache Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invalidate(self, request, context):
        """Invalidation & Cleanup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupExpired(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Index & Stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntries(self, request, context):
        """Database Inspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlightTicket(self, request, context):
        """Arrow Flight Data Plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & Capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReminiscenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupResponse.SerializeToString,
            ),
            'LookupBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupBatch,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchResponse.SerializeToString,
            ),
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreResponse.SerializeToString,
            ),
            'StoreBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreBatch,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'Invalidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Invalidate,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.InvalidateRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.InvalidateResponse.SerializeToString,
            ),
            'CleanupExpired': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupExpired,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredResponse.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.ClearRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.ClearResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetStatsRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetStatsResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsResponse.SerializeToString,
            ),
            'ListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesResponse.SerializeToString,
            ),
            'GetFlightTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlightTicket,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reminiscence.v1.ReminiscenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reminiscence.v1.ReminiscenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReminiscenceService(object):
    """Reminiscence gRPC Service - Control Plane API (v0.6.0)

    This service provides remote access to semantic cache operations.
    Designed as the foundation for the dual-plane architecture in v1.0.
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/Lookup',
            reminiscence_dot_api_dot_reminiscence__pb2.LookupRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/LookupBatch',
            reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.LookupBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/Store',
            reminiscence_dot_api_dot_reminiscence__pb2.StoreRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/StoreBatch',
            reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.StoreBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/CheckAvailability',
            reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invalidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/Invalidate',
            reminiscence_dot_api_dot_reminiscence__pb2.InvalidateRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.InvalidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupExpired(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/CleanupExpired',
            reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.CleanupExpiredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/Clear',
            reminiscence_dot_api_dot_reminiscence__pb2.ClearRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/CreateIndex',
            reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/GetStats',
            reminiscence_dot_api_dot_reminiscence__pb2.GetStatsRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/GetIndexStats',
            reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.GetIndexStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/ListEntries',
            reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlightTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/GetFlightTicket',
            reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.FlightTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/HealthCheck',
            reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reminiscence.v1.ReminiscenceService/GetCapabilities',
            reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesRequest.SerializeToString,
            reminiscence_dot_api_dot_reminiscence__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
